#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiRestaurante.DataSource
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="RESTAURANTE")]
	public partial class RestauranteDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public RestauranteDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["RESTAURANTEConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public RestauranteDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RestauranteDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RestauranteDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RestauranteDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<VW_LISTAR_INFORMACOES> VW_LISTAR_INFORMACOES
		{
			get
			{
				return this.GetTable<VW_LISTAR_INFORMACOES>();
			}
		}
		
		public System.Data.Linq.Table<VW_LISTA_ITEM_PEDIDO> VW_LISTA_ITEM_PEDIDO
		{
			get
			{
				return this.GetTable<VW_LISTA_ITEM_PEDIDO>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_LISTAR_INFORMACOES")]
	public partial class VW_LISTAR_INFORMACOES
	{
		
		private string _NOME;
		
		private string _CPF;
		
		private string _DT_NASCIMENTO;
		
		private int _ID_PEDIDO;
		
		private int _NR_MESA;
		
		private decimal _VL_TOTAL;
		
		private string _DT_CREATE;
		
		public VW_LISTAR_INFORMACOES()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOME", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string NOME
		{
			get
			{
				return this._NOME;
			}
			set
			{
				if ((this._NOME != value))
				{
					this._NOME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CPF", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string CPF
		{
			get
			{
				return this._CPF;
			}
			set
			{
				if ((this._CPF != value))
				{
					this._CPF = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DT_NASCIMENTO", DbType="VarChar(10)")]
		public string DT_NASCIMENTO
		{
			get
			{
				return this._DT_NASCIMENTO;
			}
			set
			{
				if ((this._DT_NASCIMENTO != value))
				{
					this._DT_NASCIMENTO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PEDIDO", DbType="Int NOT NULL")]
		public int ID_PEDIDO
		{
			get
			{
				return this._ID_PEDIDO;
			}
			set
			{
				if ((this._ID_PEDIDO != value))
				{
					this._ID_PEDIDO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NR_MESA", DbType="Int NOT NULL")]
		public int NR_MESA
		{
			get
			{
				return this._NR_MESA;
			}
			set
			{
				if ((this._NR_MESA != value))
				{
					this._NR_MESA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VL_TOTAL", DbType="Decimal(18,2) NOT NULL")]
		public decimal VL_TOTAL
		{
			get
			{
				return this._VL_TOTAL;
			}
			set
			{
				if ((this._VL_TOTAL != value))
				{
					this._VL_TOTAL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DT_CREATE", DbType="VarChar(10)")]
		public string DT_CREATE
		{
			get
			{
				return this._DT_CREATE;
			}
			set
			{
				if ((this._DT_CREATE != value))
				{
					this._DT_CREATE = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_LISTA_ITEM_PEDIDO")]
	public partial class VW_LISTA_ITEM_PEDIDO
	{
		
		private string _CLIENTE;
		
		private string _CPF;
		
		private string _DT_NASCIMENTO;
		
		private int _ID_ITEMPEDIDO;
		
		private int _ID_PEDIDO;
		
		private string _PRODUTO;
		
		private int _QTD_PEDIDO;
		
		private System.Nullable<decimal> _VL_PRODUTO;
		
		private System.Nullable<decimal> _VALORTOTAL;
		
		public VW_LISTA_ITEM_PEDIDO()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLIENTE", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string CLIENTE
		{
			get
			{
				return this._CLIENTE;
			}
			set
			{
				if ((this._CLIENTE != value))
				{
					this._CLIENTE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CPF", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string CPF
		{
			get
			{
				return this._CPF;
			}
			set
			{
				if ((this._CPF != value))
				{
					this._CPF = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DT_NASCIMENTO", DbType="VarChar(10)")]
		public string DT_NASCIMENTO
		{
			get
			{
				return this._DT_NASCIMENTO;
			}
			set
			{
				if ((this._DT_NASCIMENTO != value))
				{
					this._DT_NASCIMENTO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_ITEMPEDIDO", DbType="Int NOT NULL")]
		public int ID_ITEMPEDIDO
		{
			get
			{
				return this._ID_ITEMPEDIDO;
			}
			set
			{
				if ((this._ID_ITEMPEDIDO != value))
				{
					this._ID_ITEMPEDIDO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PEDIDO", DbType="Int NOT NULL")]
		public int ID_PEDIDO
		{
			get
			{
				return this._ID_PEDIDO;
			}
			set
			{
				if ((this._ID_PEDIDO != value))
				{
					this._ID_PEDIDO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRODUTO", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string PRODUTO
		{
			get
			{
				return this._PRODUTO;
			}
			set
			{
				if ((this._PRODUTO != value))
				{
					this._PRODUTO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[QTD PEDIDO]", Storage="_QTD_PEDIDO", DbType="Int NOT NULL")]
		public int QTD_PEDIDO
		{
			get
			{
				return this._QTD_PEDIDO;
			}
			set
			{
				if ((this._QTD_PEDIDO != value))
				{
					this._QTD_PEDIDO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VL_PRODUTO", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> VL_PRODUTO
		{
			get
			{
				return this._VL_PRODUTO;
			}
			set
			{
				if ((this._VL_PRODUTO != value))
				{
					this._VL_PRODUTO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VALORTOTAL", DbType="Decimal(29,2)")]
		public System.Nullable<decimal> VALORTOTAL
		{
			get
			{
				return this._VALORTOTAL;
			}
			set
			{
				if ((this._VALORTOTAL != value))
				{
					this._VALORTOTAL = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
